---
- hosts: all
  become: yes
  tasks:

  - name: add the postgresql repository gpg key
    apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"

  - name: add the postgresql repository
    apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" state=present

  - name: install postgresql
    apt: name=postgresql-9.5 update_cache=yes state=latest

  - name: create the postgres vagrant role
    shell: psql -c "CREATE USER vagrant WITH PASSWORD 'vagrant'"
    become_user: postgres

  - name: create the postgres ghmirror database
    shell: psql -c "CREATE DATABASE ghmirror; GRANT ALL PRIVILEGES ON DATABASE ghmirror TO vagrant"
    become_user: postgres
